name: GH Pages deploy

on:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'

      - run: yarn install
      - run: yarn build

      - name: Build example site
        run: yarn pages:generate
        env:
          NUXT_ENV_BASE_PATH: https://kolobok12309.github.io/vue-router-webcache/

      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./examples/gh-pages-nuxt/dist
