name: Jest tests

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['12', '14', '15', '16', 18']
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'
      - run: yarn install
      - run: yarn build
      - run: yarn test

  test17:
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: --openssl-legacy-provider
      strategy:
        matrix:
          node: [ '17' ]
      steps:
        - uses: actions/checkout@v2
        - name: Setup Node
          uses: actions/setup-node@v2
          with:
            node-version: ${{ matrix.node }}
            cache: 'yarn'
        - run: yarn install
        - run: yarn build
        - run: yarn test
